// Write docs/MODELS.md from docs/models.json (tools/inspect-models.mjs) and tools/playability.mjs.
import { readFile, writeFile } from 'node:fs/promises';
import { classify, classifyChild } from './playability.mjs';

const models = JSON.parse(await readFile(new URL('../docs/models.json', import.meta.url)));
const kb = b => (b / 1024).toFixed(0) + ' KB';
const esc = s => String(s).replace(/\|/g, '\\|');
const short = f => f.replace('assets/imported/', '');
const list = (a, n = 6) => a.length > n ? a.slice(0, n).join(', ') + `, … (+${a.length - n})` : a.join(', ') || '—';

const groups = [
  ['Starter scenes', /city-park|trampoline-park/],
  ['Tiny Treats — Fun Playground', /tiny-treats/],
  ['Kenney Mini Arcade', /kenney-mini-arcade/],
  ['Kenney Furniture Kit', /kenney-furniture-kit/],
  ['Kenney Mini Characters', /kenney-mini-characters/]
];

let out = `# Lammatna 3 — model inventory

Generated by \`node tools/inspect-models.mjs && node tools/model-table.mjs\` from every GLB / glTF in \`assets/imported/\` (${models.length} files).
Size is the scene bounding box in metres (x × y × z) before placement scaling.

**Playable?** — \`Yes\`: the model looks like a toy or game, so it must work (the behaviour column names the code that makes it work, and \`npm test\` checks every placed one).
\`Walk\`: a walkable structure. \`No\`: scenery that only needs a collider (or none for floors and shrubs). \`Scene\`: a starter scene whose children are listed separately below.

All files are **CC0 1.0** (see each pack's License.txt / assets/imported/README.md).

`;
for (const [title, re] of groups) {
  const rows = models.filter(m => re.test(m.file));
  out += `## ${title} (${rows.length})\n\n| File | Size on disk | Size (m) | Meshes | Triangles | Child nodes | Materials | Licence | Playable? | Behaviour |\n|---|---|---|---|---|---|---|---|---|---|\n`;
  for (const m of rows) {
    const c = classify(m.file);
    out += `| ${esc(short(m.file))} | ${kb(m.bytes)} | ${m.size.map(v => v.toFixed(2)).join(' × ')} | ${m.meshes} | ${m.triangles} | ${esc(list(m.children))} | ${esc(list(m.materials, 8))} | ${m.licence} | **${c.playable}** | ${c.behaviour} — ${esc(c.note)} |\n`;
  }
  out += '\n';
}

for (const m of models.filter(m => m.childBounds)) {
  const kinds = new Map();
  for (const ch of m.childBounds) {
    const kind = ch.name.replace(/^\d+-/, '');
    const k = kinds.get(kind) || { kind, count: 0, size: ch.max.map((v, i) => v - ch.min[i]) };
    k.count++;
    kinds.set(kind, k);
  }
  out += `## Children of ${short(m.file)} (${m.childBounds.length} nodes, ${kinds.size} kinds)\n\n| Child kind | Count | Size (m) | Playable? | Behaviour |\n|---|---|---|---|---|\n`;
  for (const k of kinds.values()) {
    const c = classifyChild(k.kind);
    out += `| ${k.kind} | ${k.count} | ${k.size.map(v => v.toFixed(2)).join(' × ')} | **${c.playable}** | ${c.behaviour} — ${c.note} |\n`;
  }
  out += '\n';
}
await writeFile(new URL('../docs/MODELS.md', import.meta.url), out);
console.log('docs/MODELS.md written');
