// The only place that imports Babylon.js: deep imports keep the mobile bundle small.
export { Engine } from '@babylonjs/core/Engines/engine.js';
export { Scene } from '@babylonjs/core/scene.js';
export { Vector3, Matrix, Quaternion } from '@babylonjs/core/Maths/math.vector.js';
export { Color3, Color4 } from '@babylonjs/core/Maths/math.color.js';
export { HemisphericLight } from '@babylonjs/core/Lights/hemisphericLight.js';
export { DirectionalLight } from '@babylonjs/core/Lights/directionalLight.js';
export { PointLight } from '@babylonjs/core/Lights/pointLight.js';
export { ShadowGenerator } from '@babylonjs/core/Lights/Shadows/shadowGenerator.js';
export { StandardMaterial } from '@babylonjs/core/Materials/standardMaterial.js';
export { DynamicTexture } from '@babylonjs/core/Materials/Textures/dynamicTexture.js';
export { Texture } from '@babylonjs/core/Materials/Textures/texture.js';
export { Mesh } from '@babylonjs/core/Meshes/mesh.js';
export { TransformNode } from '@babylonjs/core/Meshes/transformNode.js';
export { VertexData } from '@babylonjs/core/Meshes/mesh.vertexData.js';
import '@babylonjs/core/Meshes/thinInstanceMesh.js';
import '@babylonjs/core/Meshes/instancedMesh.js';
export { CreateSphere } from '@babylonjs/core/Meshes/Builders/sphereBuilder.js';
export { CreateCapsule } from '@babylonjs/core/Meshes/Builders/capsuleBuilder.js';
export { CreateCylinder } from '@babylonjs/core/Meshes/Builders/cylinderBuilder.js';
export { CreateBox } from '@babylonjs/core/Meshes/Builders/boxBuilder.js';
export { CreateGround } from '@babylonjs/core/Meshes/Builders/groundBuilder.js';
export { CreatePlane } from '@babylonjs/core/Meshes/Builders/planeBuilder.js';
export { CreateTorus } from '@babylonjs/core/Meshes/Builders/torusBuilder.js';
export { CreateDisc } from '@babylonjs/core/Meshes/Builders/discBuilder.js';
export { CreateTube } from '@babylonjs/core/Meshes/Builders/tubeBuilder.js';
export { CreateLathe } from '@babylonjs/core/Meshes/Builders/latheBuilder.js';
export { TargetCamera } from '@babylonjs/core/Cameras/targetCamera.js';
export { ParticleSystem } from '@babylonjs/core/Particles/particleSystem.js';
import '@babylonjs/core/Particles/particleSystemComponent.js';
export { ImageProcessingConfiguration } from '@babylonjs/core/Materials/imageProcessingConfiguration.js';
export { GlowLayer } from '@babylonjs/core/Layers/glowLayer.js';
